### ISSUE TITLE
panic: crypto: requested hash function is unavailable

### ISSUE THREAD

**Issue by isomorphisms** [DannyBen/gondl#2]
on Ubuntu 12.04.

```
panic: crypto: requested hash function is unavailable

goroutine 1 [running]:
crypto.Hash.New(0x5, 0x807d4a2, 0x807cd84)
	/usr/lib/go/src/pkg/crypto/crypto.go:62 +0x93
crypto/x509.(*Certificate).CheckSignature(0x18a3a000, 0x4, 0x1897780e, 0x44f, 0xa1b, ...)
	/usr/lib/go/src/pkg/crypto/x509/x509.go:391 +0x5b
crypto/x509.(*Certificate).CheckSignatureFrom(0x18a1a000, 0x18a3a000, 0x0, 0x0)
	/usr/lib/go/src/pkg/crypto/x509/x509.go:370 +0x141
----- stack segment boundary -----
crypto/x509.(*CertPool).findVerifiedParents(0x189e6a40, 0x18a1a000, 0x0, 0x0)
	/usr/lib/go/src/pkg/crypto/x509/cert_pool.go:44 +0x158
crypto/x509.(*Certificate).buildChains(0x18a1a000, 0x189e6ae0, 0xb754a274, 0x1, 0x1, ...)
	/usr/lib/go/src/pkg/crypto/x509/verify.go:198 +0x16d
crypto/x509.(*Certificate).Verify(0x18a1a000, 0x0, 0x0, 0x189e6a40, 0x189e6b00, ...)
	/usr/lib/go/src/pkg/crypto/x509/verify.go:177 +0x17a
crypto/tls.(*Conn).clientHandshake(0x189aa900, 0x0, 0x0)
	/usr/lib/go/src/pkg/crypto/tls/handshake_client.go:117 +0x1209
crypto/tls.(*Conn).Handshake(0x189aa900, 0x0, 0x0)
	/usr/lib/go/src/pkg/crypto/tls/conn.go:808 +0xc3
net/http.(*Transport).getConn(0x189529f0, 0x189c0380, 0x189c0380, 0x0)
	/usr/lib/go/src/pkg/net/http/transport.go:369 +0x398
net/http.(*Transport).RoundTrip(0x189529f0, 0x189659a0, 0x189ab000, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/http/transport.go:155 +0x23b
net/http.send(0x189659a0, 0x1898e480, 0x189529f0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/http/client.go:133 +0x325
net/http.(*Client).doFollowingRedirects(0x845c8fc, 0x189659a0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/http/client.go:227 +0x568
----- stack segment boundary -----
net/http.(*Client).Get(0x845c8fc, 0x189c3f80, 0x3a, 0xb75471d0, 0x0, ...)
	/usr/lib/go/src/pkg/net/http/client.go:176 +0x86
net/http.Get(0x189c3f80, 0x3a, 0x25, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/http/client.go:158 +0x40
main.httpGET(0x189c3f80, 0x3a, 0x0, 0x0)
	/usr/lib/go/src/cmd/go/http.go:25 +0x4d
main.bitbucketVCS(0x189c0fa0, 0x189c0fa0, 0x8282d18)
	/usr/lib/go/src/cmd/go/vcs.go:641 +0xc2
main.repoRootForImportPathStatic(0x189c0b81, 0x1d, 0x827a794, 0x0, 0x189c83e8, ...)
	/usr/lib/go/src/cmd/go/vcs.go:388 +0x62b
main.repoRootForImportPath(0x189c0b81, 0x1d, 0x80893c0, 0xb7760000)
	/usr/lib/go/src/cmd/go/vcs.go:323 +0x3c
main.downloadPackage(0x18964640, 0x1898eb40, 0x189c0b81)
	/usr/lib/go/src/cmd/go/get.go:246 +0xdec
main.download(0x189c0b81, 0x1d, 0x189a91e0, 0x18964500)
	/usr/lib/go/src/cmd/go/get.go:165 +0x785
main.download(0x189ac160, 0x19, 0x189a91e0, 0x18961b90)
	/usr/lib/go/src/cmd/go/get.go:223 +0x659
main.runGet(0x8458d70, 0x189506b0, 0x1)
	/usr/lib/go/src/cmd/go/get.go:72 +0xaa
main.main()
	/usr/lib/go/src/cmd/go/main.go:141 +0x39d

goroutine 2 [syscall]:
created by runtime.main
	/build/buildd/golang-1/src/pkg/runtime/proc.c:221

goroutine 6 [finalizer wait]:
created by runtime.gc
	/build/buildd/golang-1/src/pkg/runtime/mgc0.c:882

goroutine 7 [syscall]:
syscall.Syscall6()
	/build/buildd/golang-1/src/pkg/syscall/asm_linux_386.s:46 +0x27
syscall.EpollWait(0x6, 0x18963828, 0xa, 0xa, 0xffffffff, ...)
	/usr/lib/go/src/pkg/syscall/zerrors_linux_386.go:1780 +0x7d
net.(*pollster).WaitFD(0x18963820, 0x18993810, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/pkg/net/fd_linux.go:146 +0x12b
net.(*pollServer).Run(0x18993810, 0x0)
	/usr/lib/go/src/pkg/net/fd.go:236 +0xdf
created by net.newPollServer
	/usr/lib/go/src/pkg/net/newpollserver.go:35 +0x308
```

**Comment by DannyBen** [comment]
Seems to be related to `go get` and not specifically to gondl, if I am interpreting the findings correctly.

Some other occurrences of the same issue: 
[On Google Groups](https://groups.google.com/forum/#!topic/golang-nuts/Z7Rel3Hyl1c)
[On StackOverflow](http://stackoverflow.com/questions/23259764/install-plotinum-for-go)

Run `go version` see what you have.

Seems to work with `go version go1.2.1 linux/amd64` and not with 
`go version go1`

Run these commands to upgrade go on Ubuntu Precies ( [Source](http://stackoverflow.com/questions/17480044/how-to-install-the-current-version-of-go-in-ubuntu-precise) ):

	$ sudo apt-get install python-software-properties
	$ sudo add-apt-repository ppa:duh/golang
	$ sudo apt-get update
	$ sudo apt-get install golang
	$ go version

**Comment by vinit-ns** [comment]
@DannyBen 
Getting Error with 2nd Command:

sudo add-apt-repository ppa:duh/golang
Cannot access PPA (https://launchpad.net/api/1.0/~duh/+archive/golang) to get PPA information, please check your internet connection.
